#! /bin/sh

../sxhkd/sxhkdrc &


bspc monitor -d I II III IV V VI VII VIII IX X

# Set the border colors.
bspc config normal_border_color ${xrdb.color2:#222}
bspc config active_border_color ${xrdb.color1:#222}
bspc config focused_border_color ${xrdb.color7:#222}

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd &
polybar example &
nm-applet &
feh -bg-scale  $HOME/Pictures/wallpaper/wallpaper2.jpg &
wal -i $HOME/Pictures/wallpaper/wallpaper2.jpg &


